name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      #      Uses for affecting
      #      - run: |
      #          echo "BASE: ${{ env.NX_BASE }}"
      #          echo "HEAD: ${{ env.NX_HEAD }}"
      #      - uses: nrwl/nx-set-shas@v3
      #      - run: |
      #          echo "BASE: ${{ env.NX_BASE }}"
      #          echo "HEAD: ${{ env.NX_HEAD }}"
      - run: npm ci
      #      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx run-many --target=lint --all --parallel=3
      - run: npx nx run-many --target=test --all --parallel=3 --configuration=ci
      - run: npx nx run-many --target=build --all --parallel=3
