name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx format:check --base=origin/main
      - run: npx nx clear-cache
      - run: npx nx affected --target=test --base=origin/main --parallel --max-parallel=3
      - run: npx nx affected --target=lint --base=origin/main --parallel --max-parallel=3
      - run: npx nx affected --target=build --base=origin/main --prod --parallel --max-parallel=3
      - run: npx nx affected --target=e2e --base=origin/main --prod --parallel --max-parallel=3
      - name: 'Upload to Firebase HOSTING'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIZMUI }}'
          expires: 30d
          projectId: prizmui
