name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  pr_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Install Cypress
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Save cache
        id: cache-save
        uses: actions/cache/restore@v3
        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' && always() }}
        with:
          path: ./node_modules
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - run: npx nx workspace-lint
      - run: npx nx format:check --base=origin/main
      - run: npx nx clear-cache
      - run: npx nx affected --target=test --base=origin/main --parallel --max-parallel=3
      - run: npx nx affected --target=lint --base=origin/main --parallel --max-parallel=3
      - run: npx nx affected --target=build --base=origin/main --prod --parallel --max-parallel=3

      - name: Run e2e cypress test
        run: npx nx affected --target=e2e --base=origin/main --prod --parallel --max-parallel=3

      - name: 'Build doc app for firebase hosting'
        run: npx nx build doc
      - name: 'Upload to Firebase HOSTING'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIZMUI }}'
          expires: 5d
          projectId: prizmui
