name: On PR merged send message to issue
on:
  pull_request_target:
    types: [closed]

jobs:
  if_merged:
    if:
      github.event.pull_request.merged == true:
      runs-on: ubuntu-latest
      steps:
        - uses: actions-cool/pr-extract-issues@v1
          with:
            way: 'body'
            issues-labels: 'merged'
            remove-labels: 'in_progress, released'
            issues-comment: |
              Привет! Этот issue: ${number} cлит в main。
            issues-close: false
