name: Pre-released
on:
  release:
    types:
      - prereleased
  workflow_dispatch:
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  #  pre_draft_release_v1:
  #    uses: zyfra/Prizm/.github/workflows/beta-publish-ng14.yml@main
  #    secrets: inherit
  #
  #  pre_draft_release_v2:
  #    uses: zyfra/Prizm/.github/workflows/beta-publish-ng15.yml@main
  #    secrets: inherit
  #
  #  pre_draft_release_v3:
  #    uses: zyfra/Prizm/.github/workflows/beta-publish-ng16.yml@main
  #    secrets: inherit

  pre_release_v1:
    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng14.yml@main
    secrets: inherit
  #    needs: pre_draft_release_v1

  pre_release_v2:
    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng15.yml@main
    secrets: inherit
  #    needs: pre_draft_release_v2

  pre_release_v3:
    uses: zyfra/Prizm/.github/workflows/pre-release-publish-ng16.yml@main
    secrets: inherit
#    needs: pre_draft_release_v3
#  check_package_install:
#    uses: zyfra/Prizm/.github/workflows/check-build-in-real-project-ng-15.yml@main
#    secrets: inherit
#    needs: pre_draft_release
