name: Pre-released
on:
  release:
    types:
      - prereleased
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: write
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  pre_draft_release:
    uses: zyfra/Prizm/.github/workflows/draft-publish.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  pre_release:
    uses: zyfra/Prizm/.github/workflows/prerelease-publish.yml@main
    needs: pre_draft_release
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
