name: Pre-released
on:
  release:
    types: [prereleased]
  workflow_dispatch:
permissions:
  contents: read
  packages: write
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -ls
      - run: pwd
      - name: Run workflow with draft publish
        uses: ./.github/workflows/draft-publish.yml

  pre_release:
    runs-on: ubuntu-latest
    needs: draft_release
    steps:
      - uses: actions/checkout@v2
      - name: Run workflow with prerelease publish
        uses: ./.github/workflows/prerelease-publish.yml
