name: Publish package
on:
  release:
    types: [created]
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-modules-

      - name: Save cache
        id: cache-save
        uses: actions/cache/restore@v3
        if: always()
        with:
          path: ./node_modules
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - run: npx nx clear-cache
      - run: npx nx affected:build --all --prod --parallel --max-parallel=3
      - run: cd dist/libs/components && npm publish --verbose || exit_code=0
      - run: cd dist/libs/helpers && npm publish --verbose || exit_code=0
      - run: cd dist/libs/core && npm publish --verbose || exit_code=0
      - run: cd dist/libs/schematics && npm publish --verbose || exit_code=0
      - run: cd dist/libs/theme && npm publish --verbose || exit_code=0
      - run: cd dist/libs/charts && npm publish --verbose || exit_code=0
      - run: cd dist/libs/icons/base && npm publish --verbose || exit_code=0
      - run: cd dist/libs/icons/flags && npm publish --verbose || exit_code=0
