name: Released
on:
  release:
    types:
      - released
  workflow_dispatch:
permissions:
  contents: read
  packages: write
steps:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
jobs:
  pre_draft_release:
    runs-on: ubuntu-latest
    uses: zyfra/Prizm/.github/workflows/draft-publish.yml@main
    permissions:
      contents: read
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: pre_draft_release
    uses: zyfra/Prizm/.github/workflows/main-publish.yml@main
    permissions:
      contents: read
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
